version: "3"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

volumes:
  postgres: